services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/app/static
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=dpg-ctm5pfi3esus739nbpv0-a.frankfurt-postgres.render.com
      - DB_PORT=5432
      - DB_NAME=nikhil_qmz4
      - DB_USER=nikhil_qmz4_user
      - DB_PASS=cBGWpZONX1LT8FYhVlM6J0jvevvqnVJp
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nikhil_qmz4
      - POSTGRES_USER=nikhil_qmz4_user
      - POSTGRES_PASSWORD=cBGWpZONX1LT8FYhVlM6J0jvevvqnVJp
